openapi: 3.0.0
info:
  title: API de Carts
  version: 1.0.0
paths:
  /api/cart:
    get:
      summary: Busca y muestra el cart del user
      tags:
        - Carts
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cart'
        "500":
          description: Error Interno
    post:
      summary: Crea un nuevo carrito en la base de datos
      tags:
        - Carts
      responses:
        "201":
          description: Carrito creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "500":
          description: Error Interno
  /api/cart/{cid}:
    get:
      summary: Muestra un carrito específico por su ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a mostrar
          schema:
            type: string
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "404":
          description: El carrito no existe
        "500":
          description: Error Interno
    put:
      summary: Actualiza un carrito específico por su ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a actualizar
          schema:
            type: string
      requestBody:
        description: Lista de productos y cantidades a actualizar en el carrito
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  product:
                    type: string
                    description: ID del producto
                  quantity:
                    type: integer
                    description: Cantidad del producto
      responses:
        "200":
          description: Carrito actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "400":
          description: Error en la petición por cantidad inválida
        "403":
          description: No cuenta con los permisos adecuados
        "404":
          description: El carrito o el producto no existe
        "500":
          description: Error Interno
    delete:
      summary: Vacía un carrito específico por su ID
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito a vaciar
          schema:
            type: string
      responses:
        "204":
          description: Carrito vaciado exitosamente
        "403":
          description: No cuenta con los permisos adecuados
        "404":
          description: El carrito no existe
        "500":
          description: Error Interno
  /api/cart/{cid}/product/{pid}:
    post:
      summary: Agrega producto al carrito específico
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito al que se agregará el producto
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Producto agregado exitosamente al carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "404":
          description: Carrito o producto no encontrado
        "500":
          description: Error en el servidor
    delete:
      summary: Elimina un producto de un carrito específico
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito del que se eliminará el producto
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado exitosamente del carrito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "403":
          description: No cuenta con los permisos adecuados
        "404":
          description: El carrito o el producto no existe
        "500":
          description: Error Interno
    put:
      summary: Actualizar cantidad de producto en el carrito específico
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
        - name: pid
          in: path
          required: true
          description: ID del producto a actualizar
          schema:
            type: string
      requestBody:
        description: Cantidad a actualizar del producto en el carrito
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  description: Cantidad del producto
      responses:
        "200":
          description: Cantidad actualizada exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Cart'
        "403":
          description: No cuenta con los permisos adecuados
        "404":
          description: El carrito o el producto no existe
        "500":
          description: Error Interno
  /api/cart/{cid}/clear:
    put:
      summary: Vaciar carrito
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        "200":
          description: Carrito vaciado con éxito
        "404":
          description: Carrito no encontrado
        "500":
          description: Error en el servidor
  /api/cart/{cid}/purchase:
    post:
      summary: Genera un ticket de compra para un carrito específico
      tags:
        - Carts
      parameters:
        - name: cid
          in: path
          required: true
          description: ID del carrito
          schema:
            type: string
      responses:
        "201":
          description: Ticket de compra generado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ticket'
        "403":
          description: No cuenta con los permisos adecuados
        "404":
          description: El carrito no existe
        "500":
          description: Error Interno

components:
  schemas:
    Cart:
      type: object
      properties:
        _id:
          type: string
          description: ID del carrito
        products:
          type: array
          items:
            type: object
            properties:
              product:
                type: string
                description: ID del producto
              quantity:
                type: integer
                description: Cantidad del producto
      example:
        _id: "60a6c7e9f99b4b23c8f5b5a3"
        products:
          - product: "60a6c7e9f99b4b23c8f5b5a4"
            quantity: 2
    Ticket:
      type: object
      properties:
        _id:
          type: string
          description: ID del ticket
        cid:
          type: string
          description: ID del carrito
        totalAmount:
          type: number
          description: Monto total de la compra
        purchaseDate:
          type: string
          format: date-time
          description: Fecha de la compra
      example:
        _id: "6699078c94d150818d996ec7"
        cid: "6619078c94d150818d996ec7"
        totalAmount: 1500.00
        purchaseDate: "2024-06-27T10:45:00Z"
