openapi: 3.0.1
info:
  title: API de Andrés
  description: Documentación de la API de Andrés para CoderH
  version: 1.0.0
paths:
  /api/carts:
    $ref: './cart.yaml'
  /api/createProduct:
    $ref: './createProduct.yaml'
  /api/products:
    $ref: './products.yaml'
  /api/cartsRepository:
    $ref: './cartsRepository.yaml'
  /api/productsRepository:
    $ref: './productsRepository.yaml'
  /api/cartController:
    $ref: './cartController.yaml'
  /api/productController:
    $ref: './productController.yaml'
  /api/daoCarts:
    $ref: './daoCarts.yaml'
  /api/daoProducts:
    $ref: './daoProducts.yaml'
components:
  schemas:
    $ref: './schemas.yaml'
