paths:
  /api/products:
    get:
      summary: Obtener todos los productos
      tags:
        - ProductsRepository
      parameters:
        - name: page
          in: query
          description: Número de página
          schema:
            type: integer
        - name: limit
          in: query
          description: Límite de productos por página
          schema:
            type: integer
        - name: sort
          in: query
          description: Orden de los productos (ascendente o descendente)
          schema:
            type: string
        - name: category
          in: query
          description: Categoría de los productos
          schema:
            type: string
        - name: availability
          in: query
          description: Disponibilidad de los productos
          schema:
            type: string
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        "500":
          description: Error en el servidor
    post:
      summary: Agregar un nuevo producto
      tags:
        - ProductsRepository
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewProduct'
      responses:
        "201":
          description: Producto agregado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "400":
          description: Datos inválidos
        "500":
          description: Error en el servidor
  /api/products/{productId}:
    get:
      summary: Obtener producto por ID
      tags:
        - ProductsRepository
      parameters:
        - name: productId
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Operación exitosa
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
    put:
      summary: Actualizar producto por ID
      tags:
        - ProductsRepository
      parameters:
        - name: productId
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProduct'
      responses:
        "200":
          description: Producto actualizado con éxito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor
    delete:
      summary: Eliminar producto por ID
      tags:
        - ProductsRepository
      parameters:
        - name: productId
          in: path
          required: true
          description: ID del producto
          schema:
            type: string
      responses:
        "200":
          description: Producto eliminado con éxito
        "404":
          description: Producto no encontrado
        "500":
          description: Error en el servidor

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: ID del producto
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: integer
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
      example:
        _id: "60a6c7e9f99b4b23c8f5b5a3"
        title: Producto de prueba
        description: Descripción del producto de prueba
        price: 100.0
        stock: 10
        category: Prueba
    NewProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: integer
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
      example:
        title: Producto de prueba
        description: Descripción del producto de prueba
        price: 100.0
        stock: 10
        category: Prueba
    UpdateProduct:
      type: object
      properties:
        title:
          type: string
          description: Nombre del producto
        description:
          type: string
          description: Descripción del producto
        price:
          type: number
          description: Precio del producto
        stock:
          type: integer
          description: Stock del producto
        category:
          type: string
          description: Categoría del producto
      example:
        title: Producto actualizado
        description: Descripción actualizada del producto
        price: 150.0
        stock: 15
        category: Prueba

securitySchemes:
  bearerAuth:
    type: http
    scheme: bearer
    bearerFormat: JWT
